### PR TITLE
fix(linux): move deviceID to data path

### LINKED ISSUE #4: Move device ID to data dir?
Storing a device ID inside a home directory on Linux doesn't work in several scenarios:
* Docker will discard the home dir after container destruction unless instructed otherwise.
* System users often do not have a home dir.

If you agree with moving the device ID to the data dir, I can create a PR. However, I'd like to ask a couple of questions:
1. Can I ignore the device ID in the home directory and create a new one in the data dir? Maybe this is too radical, but worth a try. =)
2. If not, is it enough to copy the device ID from the home dir if there is no device ID in the data dir? Or should the home dir be used (if available) to try to sync device IDs from different data dirs?

Here is a link to the relevant function:
https://github.com/getlantern/lantern-headless-client/blob/c1e3ddc1f5d7a3ad6bc4ba3f29d7cd82d25ab253/deviceid/deviceid_nonwindows.go#L16-L46

### PR DESCRIPTION
**Pull request by magras**
closes #4

### CODE REVIEW

File: deviceid/deviceid_nonwindows.go [hunk 1]
```diff
@@ -14,33 +14,49 @@ import (
...
 	if err != nil {
-		pterm.Debug.Println("Storing new deviceID")
-		_deviceID, err := uuid.NewRandom()
-		if err != nil {
-			pterm.Error.Printfln("Error generating new deviceID, defaulting to old-style device ID, error: %s", err.Error())
-			return OldStyleDeviceID()
+		deviceID := readFromHomeDir()
+		if deviceID == "" {
+			deviceID = newDeviceId()
 		}
```
Comment (reflog) [inline deviceid/deviceid_nonwindows.go:26]:
```suggestion
		deviceID := readFromHomeDir()
```
and move:
```
		if deviceID == "" {
			deviceID = newDeviceId()
}
```
inside readFromHomeDir

File: deviceid/deviceid_nonwindows.go [hunk 2]
```diff
@@ -14,33 +14,49 @@ import (
...
-		deviceID := _deviceID.String()
+		pterm.Debug.Println("Storing deviceID")
```
Comment (reflog) [inline deviceid/deviceid_nonwindows.go]: let's remove all the `pterm.Debug`, they don't really contribute anything

File: deviceid/deviceid_nonwindows.go [hunk 3]
```diff
@@ -14,33 +14,49 @@ import (
...
 		return string(existing)
 	}
+
+}
+
+// Returns a deviceID stored at `$HOME/.lanternsecrets/.deviceid`.
+// If the file isn't readable, an empty string is returned.
+// This location was used by earlier versions of the client.
+func readFromHomeDir() string {
+	pterm.Debug.Println("Reading deviceID from home directory")
```
Comment (reflog) [inline deviceid/deviceid_nonwindows.go]:
```suggestion
// readFromHomeDir returns a deviceID stored at `$HOME/.lanternsecrets/.deviceid`.
// If the file isn't readable, a new ID is generated.
// This location was used by earlier versions of the client.
func readFromHomeDir() string {
	pterm.Debug.Println("Reading deviceID from home directory")
```

File: deviceid/deviceid_nonwindows.go [hunk 4]
```diff
@@ -14,33 +14,49 @@ import (
...
+	filename := filepath.Join(appdir.InHomeDir(".lanternsecrets/.deviceid"))
+	deviceID, err := os.ReadFile(filename)
+	if err != nil {
+		return ""
```
Comment (reflog) [inline deviceid/deviceid_nonwindows.go:46]:
```suggestion
		return newDeviceId()
```

**Review by reflog — CHANGES_REQUESTED** [review]
mostly ok, left some notes

File: deviceid/deviceid_nonwindows.go (hunk 1 above)
Comment (magras) [reply deviceid/deviceid_nonwindows.go:26]: I politely disagree. In my opinion a function should do one thing described in its name. Generating a new device ID inside the `readFromHomeDir` function would be confusing for a future reader.

However if you feel this is the better approach, I will implement it.

File: deviceid/deviceid_nonwindows.go (hunk 3 above)
Comment (magras) [reply deviceid/deviceid_nonwindows.go]: Partially applied. Only added the function name to the beginning.

**Review by reflog — APPROVED** [review]
👍🏻

**Comment by reflog** [comment]
thanks @magras
